### ISSUE TITLE
Formatter doesn't work with cucumber >= 2.0.0

### ISSUE THREAD

**Issue by madAndroid** [scalefactory/vagrant-cucumber#10]
We're seeing an old issue re-surface where the output for the cucumber run is delayed ... in these instances, it turns out that cucumber version 2.0.0 has been installed into `~/.vagrant.d/gems/gems` .. not sure exactly why the formatter fails, haven't dug into it yet, but it may be prudent to pin the version in the gemspec to < 2.0.0 for now until we can fully support cucumber > 2.0.0

**Comment by phyber** [comment]
Additionally, Cucumber 2.0.0 gives multiline arguments (such as LDIFs in .feature tests) their own type instead of passing them along as a string. @xmlrpc.call (XMLRPC::Client) doesn't know how to handle this type and fails.
